#!/bin/sh
# Emit the Homebrew formula for a release on stdout, with download URLs and
# checksums taken from the release's SHA256SUMS file.
#
# Usage: scripts/release/brew-formula.sh <version> <SHA256SUMS> > mentat.rb
set -eu

version="$1"
sums="$2"

sha_for() {
  sha="$(awk -v f="mentat-$1.tar.gz" '$2 == f { print $1 }' "$sums")"
  if [ -z "$sha" ]; then
    echo "brew-formula.sh: no checksum for mentat-$1.tar.gz in $sums" >&2
    exit 1
  fi
  printf '%s' "$sha"
}

base="https://github.com/invariant-hq/mentat/releases/download/$version"

# Resolved outside the heredoc: a command substitution failing during heredoc
# expansion is invisible to set -e, but a failing variable assignment aborts.
sha_darwin_arm64="$(sha_for darwin-arm64)"
sha_darwin_x64="$(sha_for darwin-x64)"
sha_linux_arm64="$(sha_for linux-arm64)"
sha_linux_x64="$(sha_for linux-x64)"

cat <<EOF
# Generated by scripts/release/brew-formula.sh; do not edit by hand.
class Mentat < Formula
  desc "OCaml coding agent"
  homepage "https://github.com/invariant-hq/mentat"
  version "$version"
  license "ISC"

  on_macos do
    on_arm do
      url "$base/mentat-darwin-arm64.tar.gz"
      sha256 "$sha_darwin_arm64"
    end
    on_intel do
      url "$base/mentat-darwin-x64.tar.gz"
      sha256 "$sha_darwin_x64"
    end
  end

  on_linux do
    on_arm do
      url "$base/mentat-linux-arm64.tar.gz"
      sha256 "$sha_linux_arm64"
    end
    on_intel do
      url "$base/mentat-linux-x64.tar.gz"
      sha256 "$sha_linux_x64"
    end
  end

  def install
    bin.install "mentat", "mentatd"
    pkgshare.install "LICENSE", "THIRD_PARTY_NOTICES.md"
    generate_completions_from_executable(bin/"mentat", "completion",
                                         shells: [:bash, :zsh])
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/mentat --version").strip
    assert_equal version.to_s, shell_output("#{bin}/mentatd --version").strip
  end
end
EOF
